SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS C
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
    ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
LEFT JOIN 
    (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
    ) AS R 
    ON C.CAR_ID = R.CAR_ID
WHERE 
    R.CAR_ID IS NULL
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE, 
    C.CAR_ID DESC;