SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(b.REVIEW_SCORE), 2)
FROM REST_INFO a
INNER JOIN REST_REVIEW b
USING (REST_ID)
WHERE a.ADDRESS LIKE '서울%'
GROUP BY a.REST_ID
ORDER BY 6 DESC, 4 DESC;