SELECT YEAR(b.SALES_DATE) AS YEAR, MONTH(b.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT a.USER_ID) AS USERS
FROM USER_INFO a
INNER JOIN ONLINE_SALE b
USING (USER_ID)
WHERE A.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;