SELECT a.FLAVOR
FROM FIRST_HALF a
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY FLAVOR) b
USING (FLAVOR)
GROUP BY FLAVOR
ORDER BY (a.TOTAL_ORDER + b.TOTAL_ORDER) DESC
LIMIT 3;


