SELECT c.APNT_NO, a.PT_NAME, a.PT_NO, c.MCDP_CD, b.DR_NAME, c.APNT_YMD
FROM APPOINTMENT c
INNER JOIN DOCTOR b
ON c.MDDR_ID = b.DR_ID
INNER JOIN PATIENT a
ON a.PT_NO = c.PT_NO
WHERE c.APNT_YMD LIKE '2022-04-13%' AND c.MCDP_CD = 'CS' AND c.APNT_CNCL_YN = 'N'
ORDER BY c.APNT_YMD ASC;
