-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)
SELECT HOURS.HOUR AS HOUR, COUNT(a.ANIMAL_ID) AS COUNT
FROM HOURS
LEFT JOIN ANIMAL_OUTS a ON HOURS.HOUR = HOUR(a.DATETIME)
GROUP BY HOURS.HOUR
ORDER BY HOURS.HOUR;