WITH FilteredCars AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= DATE('2022-08-01') 
      AND START_DATE < DATE('2022-11-01')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
SELECT 
    MONTH(START_DATE) AS MONTH, 
    CAR_ID, 
    COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= DATE('2022-08-01') 
  AND START_DATE < DATE('2022-11-01')
  AND CAR_ID IN (SELECT CAR_ID FROM FilteredCars)
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH(START_DATE), CAR_ID DESC;