SELECT a.FLAVOR
FROM FIRST_HALF a
INNER JOIN ICECREAM_INFO b
ON a.FLAVOR = b.FLAVOR
WHERE b.INGREDIENT_TYPE = 'fruit_based'
GROUP BY a.FLAVOR
HAVING SUM(TOTAL_ORDER) > 3000
ORDER BY SUM(TOTAL_ORDER) DESC;