SELECT a.ID, b.FISH_NAME, a.LENGTH
FROM FISH_INFO a
INNER JOIN FISH_NAME_INFO b
USING (FISH_TYPE)
WHERE a.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = a.FISH_TYPE
)
ORDER BY a.ID;