SELECT SUM(c.SCORE) AS SCORE, b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM HR_DEPARTMENT a
INNER JOIN HR_EMPLOYEES b
USING (DEPT_ID)
INNER JOIN HR_GRADE c
USING (EMP_NO)
GROUP BY c.EMP_NO, c.YEAR
ORDER BY SCORE DESC
LIMIT 1;