SELECT a.CATEGORY, a.PRICE AS MAX_PRICE, a.PRODUCT_NAME
FROM FOOD_PRODUCT a
INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS b 
ON a.CATEGORY = b.CATEGORY AND a.PRICE = b.MAX_PRICE
ORDER BY b.MAX_PRICE DESC;
