WITH CODES AS (
    SELECT
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_END,
        MAX(CASE WHEN NAME = 'Python' THEN CODE END) AS PYTHON,
        MAX(CASE WHEN NAME = 'C#' THEN CODE END) AS CSHARP
    FROM SKILLCODES
)

SELECT
    CASE
        WHEN d.SKILL_CODE & c.FRONT_END AND d.SKILL_CODE & c.PYTHON THEN 'A'
        WHEN d.SKILL_CODE & c.CSHARP THEN 'B'
        WHEN d.SKILL_CODE & c.FRONT_END THEN 'C'
    END AS GRADE,
    d.ID,
    d.EMAIL
FROM DEVELOPERS d
JOIN CODES c ON 1 = 1
WHERE
    (d.SKILL_CODE & c.FRONT_END AND d.SKILL_CODE & c.PYTHON)
    OR (d.SKILL_CODE & c.CSHARP)
    OR (d.SKILL_CODE & c.FRONT_END)
ORDER BY GRADE, d.ID;